name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 워크플로우 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        # 이 단계에서 wrangler도 설치됨 (package.json의 devDependencies)
        run: npm ci

      # Build Worker 단계는 wrangler deploy가 포함하므로 별도 실행 불필요

      - name: Deploy Worker
        # npx wrangler deploy 실행 (CI 환경에서 인증 필요)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} # GitHub Secrets 사용
        run: npx wrangler deploy index.js --name file-api --compatibility-date=2025-04-24 --kv=FILE_API_KV --r2=FILES --compatibility-flag=nodejs_compat --latest

      # --- Terraform 관련 단계는 모두 삭제됨 ---